<?php
			$optionsArray = array( 'list' => array( 'inlineAdd' => false,
'detailsAdd' => false,
'inlineEdit' => false,
'spreadsheetMode' => false,
'reorderRows' => false,
'addToBottom' => false,
'delete' => false,
'updateSelected' => false,
'addInPopup' => null,
'editInPopup' => null,
'viewInPopup' => false,
'clickSort' => true,
'sortDropdown' => false,
'showHideFields' => false,
'reorderFields' => false ),
'listSearch' => array( 'alwaysOnPanelFields' => array(  ),
'searchPanel' => false,
'fixedSearchPanel' => false,
'simpleSearchOptions' => false,
'searchSaving' => false ),
'totals' => array( 'ido' => array( 'totalsType' => '' ),
'nomeo' => array( 'totalsType' => '' ),
'racao' => array( 'totalsType' => '' ),
'sexoo' => array( 'totalsType' => '' ),
'idadeo' => array( 'totalsType' => '' ),
'coro' => array( 'totalsType' => '' ),
'textoo' => array( 'totalsType' => '' ),
'image_db' => array( 'totalsType' => '' ),
'th_image_db' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'image_db',
'nomeo' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'filterFields' => array(  ),
'inlineAddFields' => array(  ),
'inlineEditFields' => array(  ),
'fieldItems' => array( 'nomeo' => array( 'simple_grid_field1',
'simple_grid_field' ),
'image_db' => array( 'simple_grid_field7' ) ),
'hideEmptyFields' => array(  ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => true,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'above-grid' => array( 'details_found',
'page_size' ),
'below-grid' => array( 'pagination' ),
'supertop' => array(  ),
'left' => array(  ),
'top' => array(  ),
'grid' => array( 'simple_grid_field7',
'simple_grid_field',
'simple_grid_field1',
'grid_view' ) ),
'formXtTags' => array( 'above-grid' => array( 'details_found',
'recsPerPage' ),
'below-grid' => array( 'pagination' ),
'supertop' => array(  ),
'left' => array(  ),
'top' => array(  ) ),
'itemForms' => array( 'details_found' => 'above-grid',
'page_size' => 'above-grid',
'pagination' => 'below-grid',
'simple_grid_field7' => 'grid',
'simple_grid_field' => 'grid',
'simple_grid_field1' => 'grid',
'grid_view' => 'grid' ),
'itemLocations' => array( 'simple_grid_field7' => array( 'location' => 'grid',
'cellId' => 'cell_label' ),
'simple_grid_field' => array( 'location' => 'grid',
'cellId' => 'cell_label1' ),
'simple_grid_field1' => array( 'location' => 'grid',
'cellId' => 'cell_label1' ),
'grid_view' => array( 'location' => 'grid',
'cellId' => 'cell_label2' ) ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'page_size' => array( 'page_size' ),
'details_found' => array( 'details_found' ),
'pagination' => array( 'pagination' ),
'grid_view' => array( 'grid_view' ),
'-' => array( '-',
'-1',
'-2',
'-3' ),
'grid_field' => array( 'simple_grid_field1',
'simple_grid_field7' ),
'grid_field_label' => array( 'simple_grid_field' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'cell_top' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array( 'image_db_fieldcolumn' ),
'items' => array( 'simple_grid_field7' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label1' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array( 'nomeo_fieldheadercolumn',
'nomeo_fieldcolumn' ),
'items' => array( 'simple_grid_field',
'simple_grid_field1' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label2' => array( 'cols' => array( 0 ),
'rows' => array( 3 ),
'tags' => array( 'view_column' ),
'items' => array( 'grid_view' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_dpreview' => array( 'cols' => array( 0 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 5 ) ) ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array( 'details_found' => array( 'tag' => 'DISPLAYING',
'type' => 2 ) ) ),
'gridType' => 1,
'recsPerRow' => 5,
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'misc' => array( 'type' => 'list',
'breadcrumb' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'dataGrid' => array( 'groupFields' => array(  ) ) );
			$pageArray = array( 'id' => 'list',
'type' => 'list',
'layoutId' => 'topbar',
'disabled' => 0,
'default' => 1,
'forms' => array( 'above-grid' => array( 'modelId' => 'list-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c2',
'colspan' => 1 ) ),
'section' => '' ) ),
'cells' => array( 'c2' => array( 'model' => 'c2',
'items' => array( 'details_found',
'page_size' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'list-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'pagination' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'supertop' => array( 'modelId' => 'topbar-menu',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1',
'colspan' => 1 ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'left' => array( 'modelId' => 'list-vbar',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'list-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'vertical-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'cell_top',
'colspan' => 1 ) ),
'section' => 'head' ),
array( 'cells' => array( array( 'cell' => 'cell_label',
'colspan' => 1 ) ),
'section' => 'body' ),
array( 'cells' => array( array( 'cell' => 'cell_label1',
'colspan' => 1 ) ),
'section' => 'body' ),
array( 'cells' => array( array( 'cell' => 'cell_label2',
'colspan' => 1 ) ),
'section' => 'body' ),
array( 'cells' => array( array( 'cell' => 'cell_dpreview',
'colspan' => 1 ) ),
'section' => 'foot' ) ),
'cells' => array( 'cell_top' => array( 'model' => 'cell_top',
'items' => array(  ) ),
'cell_dpreview' => array( 'model' => 'cell_dpreview',
'items' => array(  ) ),
'cell_label' => array( 'model' => 'cell_label',
'items' => array( 'simple_grid_field7' ),
'align' => 'left',
'field' => 'image_db',
'columnName' => 'field' ),
'cell_label1' => array( 'model' => 'cell_label',
'items' => array( 'simple_grid_field',
'simple_grid_field1' ),
'align' => 'left',
'field' => 'nomeo',
'columnName' => 'field' ),
'cell_label2' => array( 'model' => 'cell_label',
'items' => array( 'grid_view' ),
'align' => 'left' ) ),
'deferredItems' => array(  ),
'recsPerRow' => 5 ) ),
'items' => array( 'page_size' => array( 'type' => 'page_size' ),
'details_found' => array( 'type' => 'details_found' ),
'pagination' => array( 'type' => 'pagination' ),
'grid_view' => array( 'type' => 'grid_view',
'popup' => false,
'tooltip' => array( 'type' => 0,
'text' => 'Detalhes' ),
'label' => array( 'type' => 0,
'text' => 'Detalhes' ),
'icon' => array( 'glyph' => 'plus' ) ),
'-' => array( 'type' => '-' ),
'-1' => array( 'type' => '-' ),
'-2' => array( 'type' => '-' ),
'-3' => array( 'type' => '-' ),
'simple_grid_field1' => array( 'field' => 'nomeo',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false,
'clickSort' => true ),
'simple_grid_field7' => array( 'field' => 'image_db',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false,
'clickSort' => true ),
'simple_grid_field' => array( 'type' => 'grid_field_label',
'field' => 'nomeo',
'clickSort' => true ) ),
'dbProps' => array(  ),
'spreadsheetGrid' => false,
'version' => 11,
'pageWidth' => 'full',
'reorderRows' => false,
'reorderRowsField' => '',
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right' );
		?>